<div id="comics">
    <?php if ($this->comics) : ?>
    <h1><?php echo $this->comics->xkcd_title; ?></h1>
    <img src="<?php echo '/images/' . $this->comics->xkcd_filename; ?>"
         alt="<?php echo $this->comics->xkcd_title; ?>"
         title="<?php echo $this->comics->xkcd_description; ?>"/>
    <div id="transcript"><?php echo nl2br($this->comics->xkcd_transcription); ?></div>
    <?php endif; ?>
</div>