<div id="comics">
    <div class="pagination"><?php echo $this->pagination; ?></div>
    <h2><?php echo $this->comics['xkcd_title']; ?></h2>
    <img src="<?php echo '/images/' . $this->comics['xkcd_filename']; ?>"
        alt="<?php echo $this->comics['xkcd_title']; ?>"
        title="<?php echo $this->comics['xkcd_description']; ?>"/>
    <div class="transcript"><?php echo nl2br($this->comics['xkcd_transcription']); ?></div>
    <div class="pagination"><?php echo $this->pagination; ?></div>
</div>